runtime: python39

entrypoint: gunicorn -b :$PORT run:app

env_variables:
  SECRET_KEY: "your-secret-key-replace-this-in-production"
  TWILIO_ACCOUNT_SID: "your-twilio-account-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_PHONE_NUMBER: "your-twilio-phone-number"

handlers:
- url: /.*
  script: auto

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1 